# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20160803_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='statics/imgs/upload/'),
        ),
    ]
