# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20160803_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='imgs/upload/'),
        ),
    ]
