# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webqq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqgroup',
            name='members',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile'), related_name='members', to='bbs.UserProfile'),
        ),
    ]
